name: yapastillas
description: AplicaciÃ³n para gestionar medicamentos y recordatorios de tomas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
